<#
.SYNOPSIS
    Builds and signs all sparse-package subfolders in the repository.

.DESCRIPTION
    For every subdirectory that contains an AppxManifest.xml this script:
      1. Runs MakeAppx.exe to produce a .msix file in the _output\ directory.
      2. Signs the .msix with SignTool.exe using a local PFX (dev) or via the
         Azure Trusted Signing (formerly Azure Artifact Signing) service (prod).

    Prerequisites:
      - Windows SDK installed (provides MakeAppx.exe and SignTool.exe).
        Default search path: C:\Program Files (x86)\Windows Kits\10\bin\<version>\x64
      - For dev signing: a PFX certificate file (generated by New-DevCertificate.ps1).
      - For Azure Trusted Signing: the Microsoft.Trusted.Signing.Client NuGet package
        and the dlib authenticode plugin (see README for setup).

.PARAMETER OutDir
    Directory where .msix output files are written.  Default: .\_output

.PARAMETER PfxPath
    Path to a .pfx file for local development signing.
    Mutually exclusive with -AzureTrustedSigning.

.PARAMETER PfxPassword
    Password for the PFX file.  Will be prompted interactively if not supplied.

.PARAMETER AzureTrustedSigning
    Switch: sign using Azure Trusted Signing instead of a local PFX.
    Requires -TrustedSigningEndpoint, -TrustedSigningAccountName, and
    -TrustedSigningCertificateProfileName.

.PARAMETER TrustedSigningEndpoint
    Azure Trusted Signing endpoint URI.
    Example: https://eus.codesigning.azure.net

.PARAMETER TrustedSigningAccountName
    The name of the Azure Trusted Signing account.

.PARAMETER TrustedSigningCertificateProfileName
    The certificate profile name within the Trusted Signing account.

.EXAMPLE
    # Dev build with local certificate
    .\Build-Packages.ps1 -PfxPath DevCert.pfx

.EXAMPLE
    # Production build via Azure Trusted Signing
    .\Build-Packages.ps1 -AzureTrustedSigning `
        -TrustedSigningEndpoint https://eus.codesigning.azure.net `
        -TrustedSigningAccountName MySigningAccount `
        -TrustedSigningCertificateProfileName MyProfile
#>
[CmdletBinding(DefaultParameterSetName = 'LocalPfx')]
param(
    [string] $OutDir = (Join-Path (Get-Location).Path '_output'),

    [Parameter(ParameterSetName = 'LocalPfx')]
    [string] $PfxPath,

    [Parameter(ParameterSetName = 'LocalPfx')]
    [SecureString] $PfxPassword,

    [Parameter(ParameterSetName = 'AzureTrustedSigning', Mandatory)]
    [switch] $AzureTrustedSigning,

    [Parameter(ParameterSetName = 'AzureTrustedSigning', Mandatory)]
    [string] $TrustedSigningEndpoint,

    [Parameter(ParameterSetName = 'AzureTrustedSigning', Mandatory)]
    [string] $TrustedSigningAccountName,

    [Parameter(ParameterSetName = 'AzureTrustedSigning', Mandatory)]
    [string] $TrustedSigningCertificateProfileName
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Locate Windows SDK tools (MakeAppx.exe, SignTool.exe)
# ---------------------------------------------------------------------------
function Find-SdkTool {
    param([string] $ToolName)

    $sdkRoot = 'C:\Program Files (x86)\Windows Kits\10\bin'
    if (-not (Test-Path $sdkRoot)) {
        throw "Windows SDK not found at '$sdkRoot'. Install the Windows 10/11 SDK."
    }

    # Pick the highest available version
    $tool = Get-ChildItem -Path $sdkRoot -Filter $ToolName -Recurse |
        Where-Object { $_.FullName -match '\\x64\\' } |
        Sort-Object { [version]($_.FullName -replace '.*\\bin\\([0-9.]+)\\.*', '$1') } -Descending |
        Select-Object -First 1

    if (-not $tool) {
        throw "'$ToolName' not found under '$sdkRoot'. Ensure the Windows SDK is installed."
    }
    return $tool.FullName
}

$makeAppx  = Find-SdkTool 'MakeAppx.exe'
$signTool  = Find-SdkTool 'SignTool.exe'
Write-Host "MakeAppx : $makeAppx"
Write-Host "SignTool : $signTool"

# ---------------------------------------------------------------------------
# Prompt for PFX password if needed
# ---------------------------------------------------------------------------
if ($PSCmdlet.ParameterSetName -eq 'LocalPfx' -and $PfxPath -and -not $PfxPassword) {
    $PfxPassword = Read-Host -AsSecureString "Enter password for $PfxPath"
}

# ---------------------------------------------------------------------------
# Find all packages (subdirectories with AppxManifest.xml)
# ---------------------------------------------------------------------------
$repoRoot = (Get-Location).Path
$packages = Get-ChildItem -Path $repoRoot -Filter 'AppxManifest.xml' -Recurse -File |
    Where-Object { $_.DirectoryName -ne $repoRoot }

if ($packages.Count -eq 0) {
    Write-Warning 'No AppxManifest.xml files found in subdirectories. Nothing to build.'
    exit 0
}

New-Item -ItemType Directory -Path $OutDir -Force | Out-Null
Write-Host ""
Write-Host "Building $($packages.Count) package(s) → $OutDir" -ForegroundColor Cyan

$errors = @()

foreach ($manifest in $packages) {
    $pkgDir  = $manifest.DirectoryName
    $pkgName = Split-Path $pkgDir -Leaf
    $msixOut = Join-Path $OutDir "$pkgName.msix"

    Write-Host ""
    Write-Host "── $pkgName ──────────────────────────────────────" -ForegroundColor White

    # --- Pack -----------------------------------------------------------------
    Write-Host "  Packing: $pkgDir → $msixOut"
    & $makeAppx pack /d $pkgDir /p $msixOut /overwrite /nv
    if ($LASTEXITCODE -ne 0) {
        $errors += "MakeAppx failed for '$pkgName' (exit code $LASTEXITCODE)"
        continue
    }

    # --- Sign -----------------------------------------------------------------
    if ($PSCmdlet.ParameterSetName -eq 'LocalPfx' -and $PfxPath) {
        Write-Host "  Signing with local PFX: $PfxPath"
        $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($PfxPassword)
        try {
            $plainPwd = [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
            & $signTool sign /fd SHA256 /a /f $PfxPath /p $plainPwd $msixOut
        }
        finally {
            [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
        }
        if ($LASTEXITCODE -ne 0) {
            $errors += "SignTool failed for '$pkgName' (exit code $LASTEXITCODE)"
            continue
        }
    }
    elseif ($PSCmdlet.ParameterSetName -eq 'AzureTrustedSigning') {
        # Azure Trusted Signing via SignTool dlib plugin
        # See: https://learn.microsoft.com/azure/trusted-signing/how-to-signing-integrations
        Write-Host "  Signing with Azure Trusted Signing: $TrustedSigningAccountName/$TrustedSigningCertificateProfileName"
        $dlibPath = (Get-ChildItem -Recurse -Filter 'Azure.CodeSigning.Dlib.dll' `
            -ErrorAction SilentlyContinue | Select-Object -First 1)?.FullName
        if (-not $dlibPath) {
            $errors += "Azure.CodeSigning.Dlib.dll not found. Run: " +
                       "nuget install Microsoft.Trusted.Signing.Client"
            continue
        }
        $metadata = @{
            Endpoint                       = $TrustedSigningEndpoint
            CodeSigningAccountName         = $TrustedSigningAccountName
            CertificateProfileName         = $TrustedSigningCertificateProfileName
        } | ConvertTo-Json
        $metaFile = Join-Path $OutDir "$pkgName-signing-metadata.json"
        $metadata | Set-Content $metaFile -Encoding utf8
        & $signTool sign /fd SHA256 /p7 $OutDir /tr https://timestamp.acs.microsoft.com `
            /td SHA256 /dlib $dlibPath /dmdf $metaFile $msixOut
        Remove-Item $metaFile -Force
        if ($LASTEXITCODE -ne 0) {
            $errors += "Azure Trusted Signing failed for '$pkgName' (exit code $LASTEXITCODE)"
            continue
        }
    }
    else {
        Write-Warning "  No signing method specified. Skipping signing for '$pkgName'."
    }

    Write-Host "  ✓ $msixOut" -ForegroundColor Green
}

Write-Host ""
if ($errors.Count -gt 0) {
    Write-Host "Build completed with $($errors.Count) error(s):" -ForegroundColor Red
    $errors | ForEach-Object { Write-Host "  • $_" -ForegroundColor Red }
    exit 1
}
else {
    Write-Host "All packages built successfully → $OutDir" -ForegroundColor Green
}
